### ISSUE TITLE
Instructions to obtain issueToken not working

### ISSUE THREAD

**Issue by frakman1** [sychen52/nest-camera-site#3]
I followed the instructions to get `issueToken` by filtering the  Network capture while logging in to nest but no such packet showed up.

![image](https://user-images.githubusercontent.com/5826484/74106059-5df46580-4b31-11ea-8959-83f4645c6bb8.png)

**Comment by sychen52** [comment]
I actually had the similar issue. For me, it appears for a short moment and then disappears. I have to press the stop button of the browser immediately after I see it. But anyway, this would be a more appropriate issue to the homebridge-nest, because they may give you more info about this part of the instruction.

**Comment by frakman1** [comment]
I tried several times with no luck.

I still log in using my nest account. I haven't switched to Google. Maybe that's why.

Anyway, if it means anything, I was able to use this URL to load my camera screen today:

`https://nexusapi-us1.dropcam.com/get_image?uuid=xxxx&public=yyyy`
using the values in `View page source`

**Comment by sychen52** [comment]
I see. This repo currently only works with Google login.
